service: serverless-test

provider:
  name: aws
  runtime: python3.7
  profile: my_admin
  stage: dev
  region: eu-west-3

package:
  exclude:
    - layers/**
    - node_modules/**
    - venv/**
    - package-lock.json

layers:
  chromium:
    compatibleRuntimes:
      - python3.7
    allowedAccounts:
      - '*'
    package:
      artifact: layers/chromium/stable-headless-chromium-amazonlinux-2017-03.zip


functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: ChromiumLambdaLayer }

plugins:
  - serverless-python-requirements


custom:
  pythonRequirements:
    dockerizePip: true
